name: flutter_minimalist_audio_player
description: "This plugin is a simple UI implementation for AudioPlayer plugin. It simply display a icon button for playing media"
version: 1.1.1
repository: https://github.com/mynumeric-mobile/flutter_minimalist_audio_player

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  web:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
   
      some_platform:
        pluginClass: somePluginClass
    